---
# Debian or derivative specific tasks.

# Tasks for updating the operating system and installing additional packages.
- name: Updating the operating system and installing additional packages.
  block:
    - name: Getting guest operating system information.
      ansible.builtin.debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Updating the operating system.
      ansible.builtin.apt:
        name: "*"
        state: latest # noqa package-latest
        update_cache: true

    - name: Installing additional packages.
      ansible.builtin.apt:
        name: "{{ base_additional_packages[ansible_os_family] }}"
        state: latest # noqa package-latest

    - name: Installing cloud-init.
      ansible.builtin.apt:
        name: cloud-init
        state: latest # noqa package-latest
      when: enable_cloudinit == 'true' and ansible_distribution_version | int >= 12
