---
- name: "Updating the guest operating system."
  apt:
    force_apt_get: true
    name: "*"
    state: latest     # noqa package-latest
    update_cache: "yes"
- name: "Installing additional packages."
  apt:
    name:
      - bash-completion
      - curl
      - wget
      - git
      - net-tools
      - unzip
      - ca-certificates
    state: latest     # noqa package-latest
- name: "Importing certificate authority certificates."
  copy:
    dest: /usr/local/share/ca-certificates/
    group: root
    mode: 420
    owner: root
    src: root-ca.cer
  notify: "Ubuntu - Updating the certificate authority trust."
