---
- name: "{{ users_task_name }}"
  ansible.builtin.include_tasks: linux.yml
  when: ansible_facts['os_family'] in ['Debian', 'RedHat', 'Suse'] or ansible_facts['distribution'] == 'VMware Photon OS'
