---
version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: develop
    directory: "/"
    schedule:
      interval: weekly
      timezone: "America/New_York"
      day: "sunday"
      time: "00:00"
    labels:
      - "area/dependencies"
      - "area/github-actions"
      - "type/chore"
    commit-message:
      prefix: "chore(deps):"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "terraform"
    target-branch: develop
    directory: "/"
    schedule:
      interval: weekly
      timezone: "America/New_York"
      day: "sunday"
      time: "00:00"
    labels:
      - "area/dependencies"
      - "type/chore"
    commit-message:
      prefix: "chore(deps):"
    ignore:
      - dependency-name: "terraform"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "hashicorp/vsphere"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "hashicorp/hcp"
        update-types: ["version-update:semver-patch"]
    groups:
      terraform:
        patterns:
          - "terraform"
      terraform-vsphere:
        patterns:
          - "hashicorp/vsphere"
      terraform-hcp:
        patterns:
          - "hashicorp/hcp"
  - package-ecosystem: "pip"
    target-branch: develop
    directory: "/"
    schedule:
      interval: weekly
      timezone: "America/New_York"
      day: "sunday"
      time: "00:00"
    labels:
      - "area/dependencies"
      - "type/chore"
    commit-message:
      prefix: "chore(deps):"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
