---
name: Documentation
description: Found a typo or something that needs clarification?
title: "REPLACE WITH SHORT DESCRIPTION"
labels:
  - type/docs
  - status/needs-review
body:
  - type: markdown
    attributes:
      value: >-
        When filing an issue, please include the following information.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: >-
        This project has a Code of Conduct that all participants are expected
        to understand and follow.
      options:
        - label: I have read and agree to the project's Code of Conduct.
          required: true
  - type: dropdown
    id: version-project
    attributes:
      label: Project Version
      description: Please provide the version of this project.
      options:
        - main
        - 23.01 (latest)
        - 22.09
        - 22.08
        - 22.07
        - 22.06
        - 22.05
        - 22.04
        - 22.03
        - 22.02
        - 22.01
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why should we update our docs or examples?
    validations:
      required: false
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: What should we do instead?
    validations:
      required: false
  - type: markdown
    attributes:
      value: >-
        ## Community Note

        - Please vote on this issue by adding a reaction to the original issue
        to help the community and maintainers prioritize this request.

        - Please do not leave comments that do not add relevant new information
        or questions, they generate extra noise for issue followers and do not
        help prioritize the request

        - If you are interested in working on this issue or have submitted a
        pull request, please leave a comment.
