name: Documentation
description: Found a typo or something that needs clarification?
title: "[DOCS] REPLACE WITH SHORT DESCRIPTION"
labels: [type/docs, status/needs-review]
assignees:
  - tenthirtyam
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a [Code of Conduct](https://github.com/rainpole/packer-vsphere/blob/main/CODE_OF_CONDUCT.md) that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's Code of Conduct.
          required: true
  - type: dropdown
    id: version-project
    attributes:
      label: Project Version
      description: Please provide the version of this project.
      options:
        - main
        - 21.11 (Default)
        - 21.10.1
        - 21.10
        - 21.09.1
        - 21.09
        - 21.08
        - 21.07
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why should we update our docs or examples?
    validations:
      required: false
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: What should we do instead?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ### Community Note
        * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment
