---
name: Documentation
description: Found a typo or something that needs clarification?
title: 'REPLACE WITH SHORT DESCRIPTION'
labels:
  - type/docs
  - status/needs-review
assignees:
  - tenthirtyam
body:
  - type: markdown
    attributes:
      value: >
        When filing a documentation issue, please include the following information.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: >-
        This project has a [Code of
        Conduct](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/main/CODE_OF_CONDUCT.md)
        that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's Code of Conduct.
          required: true
  - type: dropdown
    id: version-project
    attributes:
      label: Project Version
      description: Please provide the version of this project.
      options:
        - main
        - 22.09 (latest)
        - 22.08
        - 22.07
        - 22.06
        - 22.05
        - 22.04
        - 22.03
        - 22.02
        - 22.01
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why should we update our docs or examples?
    validations:
      required: false
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: What should we do instead?
    validations:
      required: false
  - type: markdown
    attributes:
      value: "### Community Note\n* Please vote on this issue by adding a \U0001F44D [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request\n* Please do not leave \"+1\" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request\n* If you are interested in working on this issue or have submitted a pull request, please leave a comment\n"
