---
name: Enhancement Request
description: Is something critical missing? Suggest a feature or an enhancement.
title: Please add a short description.
labels:
  - type/enhancement
  - status/needs-review
body:
  - type: markdown
    attributes:
      value: >
        Before filing a feature, please search the existing issues and
        discussions for relevant feature requests. Use the reactions to add
        up-votes to existing requests.


        When filing an issue, please include the following information.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: >-
        This project has a Code of Conduct that all participants are expected
        to understand and follow.
      options:
        - label: I have read and agree to the project's Code of Conduct.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A written overview of the enhancement.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case(s)
      description: Any relevant use-cases that you see.
    validations:
      required: true
  - type: textarea
    id: potential-configuration
    attributes:
      label: Potential Configuration
      description: Provide a potential configuration.
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References
      description: Provide any references.
    validations:
      required: false
  - type: markdown
    attributes:
      value: >-
        ## Community Note

        - Please vote on this issue by adding a reaction to the original issue
        to help the community and maintainers prioritize this request.

        - Please do not leave comments that do not add relevant new information
        or questions, they generate extra noise for issue followers and do not
        help prioritize the request

        - If you are interested in working on this issue or have submitted a
        pull request, please leave a comment.
