---
- name: "Configure SSH for Public Key Authentication."
  shell: |
    sudo sed -i '/^PermitRootLogin/s/yes/no/' /etc/ssh/sshd_config
    sudo sed -i 's/.*PubkeyAuthentication.*/PubkeyAuthentication yes/g' /etc/ssh/sshd_config
- name: "Setting hostname to localhost."
  shell: |
    hostnamectl set-hostname localhost
- name: "Disable IPv6."
  shell: |
    sudo echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
