---
- name: "Cleaning tdnf cache."
  shell: |
    tdnf clean all
- name: "Cleaning log files."
  shell: |
    find /var/log -type f -delete
    rm -rf /var/log/journal/*
- name: "Cleaning SSH host keys."
  shell: |
    rm -f /etc/ssh/ssh_host_*
- name: "Cleaning the machine-id."
  shell: |
    truncate -s 0 /etc/machine-id
    rm /var/lib/dbus/machine-id
    ln -s /etc/machine-id /var/lib/dbus/machine-id
- name: "Cleaning the shell history."
  shell: |
    history -c
