---
- name: "Cleaning tdnf cache."
  shell: |
    tdnf clean all
  args:
    warn: false
- name: "Cleaning log files."
  shell: |
    find /var/log -type f -delete
    rm -rf /var/log/journal/*
  args:
    warn: false
- name: "Cleaning SSH host keys."
  shell: |
    rm -f /etc/ssh/ssh_host_*
  args:
    warn: false
- name: "Cleaning the machine-id."
  shell: |
    truncate -s 0 /etc/machine-id
    rm /var/lib/dbus/machine-id
    ln -s /etc/machine-id /var/lib/dbus/machine-id
  args:
    warn: false
- name: "Cleaning the shell history."
  shell: |
    history -c
  args:
    warn: false
