---

- hosts: localhost
  gather_facts: yes
  become: true
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"

  - block:    # For Ubuntu Distributions
    - name: Update cache and Upgrade all Installed Packages
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Packages
      apt:
        name:
          - bash-completion
          - curl
          - wget
          - git
          - net-tools
          - unzip
          - ca-certificates
        state: latest

    - name: Install CA Certificate
      copy:
        src: /tmp/root-ca.crt
        dest: /usr/local/share/ca-certificates/
        owner: root
        group: root
        mode: 0644
      notify:
      - update trusted ca ubuntu
      when:
        - ansible_distribution == "Ubuntu"

  handlers:
      - name: update trusted ca ubuntu
        shell: /usr/sbin/update-ca-certificates
